# yaml-language-server: $schema=./config-schema.json

data:
  dataset: mnist
  dirichlet_alpha: 10.0
  split_seed: 42
simulation:
  device: auto
  num_clients: 10
  timeout_seconds: 10
  client_rate_std: 0.01
  rate_seed: 42
  torch_seed: 42
model:
  model_name: cnn
mem_strategy:
  type: disabled
comm_strategy:
# Note: 'buffer_size' must be commented out when type is 'sync' and
# 'sample_size' must be commented out when type is 'async' (extra fields forbidden)
  type: sync
  # buffer_size: 4 # Only for async
  sample_size: 4 # Only for sync
optimization:
  learning_rate: 0.1
  weight_decay: 0.1
  num_local_steps: 100
  batch_size: 1
evaluation:
  batch_size: 128
  num_workers: 0
checkpoints:
  keep_best: False
  interval_seconds: 10
visualization: # requires matplotlib
  visualize_data_split: True
  visualize_client_arrivals: True
